version: "3.9"

services:

    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb-data:/data/db
            - mongodb-data:/data/configdb

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"   
        depends_on:
            - "mongodb"
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

    client-spa:
        container_name: client-spa
        image: client-spa
        build:
            context: src/frontends/client-spa
            dockerfile: Dockerfile
        ports:
            - "4000:80"

    test-service:
        container_name: test-service
        image: test-service
        build:
            context: src/backends/test-service
            dockerfile: Dockerfile
        restart: always
        ports:
            - "5000:8080"
        depends_on:
            - "mongodb"     

volumes:
    mongodb-data:
        driver: local